### ISSUE TITLE
Very low bandwith

### ISSUE THREAD

**Issue by Reen68** [bubuntux/nordvpn#166]
### Before submitting review [Troubleshooting](https://github.com/bubuntux/nordvpn/wiki/Troubleshooting) and open/closed [Issues](https://github.com/bubuntux/nordvpn/issues?q=) ###

**Describe the bug**
My NordVPN Connection using this docker container is very slow.

**To Reproduce without docker CLI**
docker-compose.yml if used  (hide credentials)
```
version: '3'
services:
  vpn:
    image: bubuntux/nordvpn
    container_name: vpn
    network_mode: bridge        # Required
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=user     # Required
      - "PASS=pass"         # Required
      - CONNECT=Belgium
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.178.1/24
      - CYBER_SEC=Disable
      - DNS=1.1.1.1
      - TZ=Europe/Berlin
```

**Expected behavior**
Higher bandwith

**Logs**
```


2021/04/24 20:41:29 [Info] Daemon has started

2021/04/24 20:41:30 Kill Switch set to: disabled

NordVPN App Connection Settings:

Technology: NordLynx

Protocol: UDP

Firewall: enabled

KillSwitch: disabled

Obfuscate: disabled

Notify: disabled

Auto-connect: disabled


2021/04/24 20:41:30 Technology set to: NordLynx

NordVPN App Connection Settings:

Technology: NordLynx

Protocol: UDP

Firewall: enabled

KillSwitch: disabled

Obfuscate: disabled

Notify: disabled

Auto-connect: disabled


2021/04/24 20:41:30 Auto-connect set to: disabled

NordVPN App Connection Settings:

Technology: NordLynx

Protocol: UDP

Firewall: enabled

KillSwitch: disabled

Obfuscate: disabled

Notify: disabled

Auto-connect: disabled


2021/04/24 20:41:30 DNS set to: enabled

NordVPN App Connection Settings:

Technology: NordLynx

Protocol: UDP

Firewall: enabled

KillSwitch: disabled

Obfuscate: disabled

Notify: disabled

Auto-connect: disabled


2021/04/24 20:41:30 Protocol set to: UDP

NordVPN App Connection Settings:

Technology: NordLynx

Protocol: UDP

Firewall: enabled

KillSwitch: disabled

Obfuscate: disabled

Notify: disabled

Auto-connect: disabled


2021/04/24 20:41:30 CyberSec set to: disabled

NordVPN App Connection Settings:

Technology: NordLynx

Protocol: UDP

Firewall: enabled

KillSwitch: disabled

Obfuscate: disabled

Notify: disabled

Auto-connect: disabled


+ '[' '!' -S /run/nordvpn/nordvpnd.sock ']'

+ nordvpn login -u ** -p **


-
  
You are already logged in.

+ [[ -n NordLynx ]]

+ nordvpn set technology NordLynx

Technology is already set to 'NordLynx'.

+ [[ -n '' ]]

+ [[ -n '' ]]

+ [[ -n Disable ]]

+ nordvpn set cybersec Disable

CyberSec is already set to 'disabled'.

+ [[ -n 1.1.1.1 ]]

+ nordvpn set dns 1.1.1.1

DNS is already set to '1.1.1.1'.

+ [[ -n 172.17.0.3/16 ]]

+ nordvpn whitelist add subnet 172.17.0.3/16

Subnet 172.17.0.0/16 is whitelisted successfully.

+ [[ -n 192.168.178.1/24 ]]

+ for net in ${NETWORK//[;,]/ }

+ nordvpn whitelist add subnet 192.168.178.1/24

Subnet 192.168.178.0/24 is whitelisted successfully.

+ [[ -n '' ]]

+ [[ -n on ]]

+ nordvpn -version

NordVPN Version 3.9.1

+ nordvpn settings


-
  

-
  
Technology: NordLynx

Firewall: enabled

Kill Switch: disabled

CyberSec: disabled

Notify: disabled

Auto-connect: disabled

DNS: 1.1.1.1

Whitelisted subnets:

	172.17.0.0/16

	192.168.178.0/24

+ mkdir -p /dev/net

+ [[ -c /dev/net/tun ]]

+ nordvpn connect Belgium


-
  

-2021/04/24 20:41:30 PRE_CONNECT system info:

App Version: 3.9.1

OS Info:

NAME="Ubuntu"

VERSION="18.04.5 LTS (Bionic Beaver)"

u

ID_LIKE=debian

PRETTY_NAME="Ubuntu 18.04.5 LTS"

VERSION_ID="18.04"

HOME_URL="https://www.ubuntu.com/"

SUPPORT_URL="https://help.ubuntu.com/"

BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"

PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"

VERSION_CODENAME=bionic

UBUNTU_CODENAME=bionic


System Info:Linux 70ebcc759161 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l armv7l armv7l GNU/Linux



Routes of All Routing Tables:

default via 172.17.0.1 dev eth0 

172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.3 

broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1 

local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1 

local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1 

broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1 

broadcast 172.17.0.0 dev eth0 table local proto kernel scope link src 172.17.0.3 

local 172.17.0.3 dev eth0 table local proto kernel scope host src 172.17.0.3 

broadcast 172.17.255.255 dev eth0 table local proto kernel scope link src 172.17.0.3 


:

0:	from all lookup local 

32766:	from all lookup main 

32767:	from all lookup default 


IP Tables:

filter:

-P INPUT DROP

-P FORWARD DROP

-P OUTPUT DROP

-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A INPUT -i lo -j ACCEPT

-A INPUT -s 172.17.0.0/16 -j ACCEPT

-A INPUT -s 192.168.178.0/24 -j ACCEPT

-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A FORWARD -i lo -j ACCEPT

-A FORWARD -d 172.17.0.0/16 -j ACCEPT

-A FORWARD -s 172.17.0.0/16 -j ACCEPT

-A FORWARD -d 192.168.178.0/24 -j ACCEPT

-A FORWARD -s 192.168.178.0/24 -j ACCEPT

-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A OUTPUT -o lo -j ACCEPT

-A OUTPUT -o tap+ -j ACCEPT

-A OUTPUT -o tun+ -j ACCEPT

-A OUTPUT -o nordlynx -j ACCEPT

-A OUTPUT -p udp -m udp --dport 53 -j ACCEPT

-A OUTPUT -p udp -m udp --dport 51820 -j ACCEPT

-A OUTPUT -p tcp -m tcp --dport 1194 -j ACCEPT

-A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT

-A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT

-A OUTPUT -d 172.17.0.0/16 -j ACCEPT

-A OUTPUT -d 192.168.178.0/24 -j ACCEPT

-A OUTPUT -d 104.17.50.74/32 -o eth0 -j ACCEPT

-A OUTPUT -d 104.17.49.74/32 -o eth0 -j ACCEPT


nat:

-P PREROUTING ACCEPT

-P INPUT ACCEPT

-P OUTPUT ACCEPT

-P POSTROUTING ACCEPT

-A POSTROUTING -o tap+ -j MASQUERADE

-A POSTROUTING -o tun+ -j MASQUERADE

-A POSTROUTING -o nordlynx -j MASQUERADE


mangle:

-P PREROUTING ACCEPT

-P INPUT ACCEPT

-P FORWARD ACCEPT

-P OUTPUT ACCEPT

-P POSTROUTING ACCEPT


raw:

-P PREROUTING ACCEPT

-P OUTPUT ACCEPT



2021/04/24 20:41:30 [Debug] picking servers for NordLynx technology


\
|
/
-
\
|
/
-
\
|
/
-
\2021/04/24 20:41:33 [Warning] route(s) for whitelisted subnet(s) via non-default gateway already exist in the system


|INFO: (nordlynx) 2021/04/24 20:41:33 Attaching to interface

INFO: (nordlynx) 2021/04/24 20:41:33 Interface set up


  
Connecting to Belgium #193 (be193.nordvpn.com)


-INFO: (nordlynx) 2021/04/24 20:41:33 Device started

2021/04/24 20:41:33 [nordlynx] ip link set mtu 1420 up dev nordlynx


\
  
You are connected to Belgium #193 (be193.nordvpn.com)!


-2021/04/24 20:41:33 POST_CONNECT system info:

Routes of All Routing Tables:

0.0.0.0/1 via 10.5.0.2 dev nordlynx 

default via 172.17.0.1 dev eth0 

10.5.0.1 dev nordlynx proto kernel scope link src 10.5.0.2 

128.0.0.0/1 via 10.5.0.2 dev nordlynx 

172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.3 

188.95.55.48 via 172.17.0.1 dev eth0 

192.168.178.0/24 via 172.17.0.1 dev eth0 

local 10.5.0.2 dev nordlynx table local proto kernel scope host src 10.5.0.2 

broadcast 127.0.0.0 dev lo table local proto kernel scope link src 127.0.0.1 

local 127.0.0.0/8 dev lo table local proto kernel scope host src 127.0.0.1 

local 127.0.0.1 dev lo table local proto kernel scope host src 127.0.0.1 

broadcast 127.255.255.255 dev lo table local proto kernel scope link src 127.0.0.1 

broadcast 172.17.0.0 dev eth0 table local proto kernel scope link src 172.17.0.3 

local 172.17.0.3 dev eth0 table local proto kernel scope host src 172.17.0.3 

broadcast 172.17.255.255 dev eth0 table local proto kernel scope link src 172.17.0.3 
:

0:	from all lookup local 

32766:	from all lookup main 

32767:	from all lookup default 


IP Tables:

filter:

-P INPUT DROP

-P FORWARD DROP

-P OUTPUT DROP

-A INPUT -s 188.95.55.48/32 -i eth0 -j ACCEPT

-A INPUT -s 172.17.0.0/16 -i eth0 -j ACCEPT

-A INPUT -s 192.168.178.0/24 -i eth0 -j ACCEPT

-A INPUT -i eth0 -j DROP

-A INPUT -s 103.86.99.100/32 -i eth0 -j ACCEPT

-A INPUT -s 103.86.96.100/32 -i eth0 -j ACCEPT

-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A INPUT -i lo -j ACCEPT

-A INPUT -s 172.17.0.0/16 -j ACCEPT

-A INPUT -s 192.168.178.0/24 -j ACCEPT

-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A FORWARD -i lo -j ACCEPT

-A FORWARD -d 172.17.0.0/16 -j ACCEPT

-A FORWARD -s 172.17.0.0/16 -j ACCEPT

-A FORWARD -d 192.168.178.0/24 -j ACCEPT

-A FORWARD -s 192.168.178.0/24 -j ACCEPT

-A OUTPUT -d 188.95.55.48/32 -o eth0 -j ACCEPT

-A OUTPUT -d 172.17.0.0/16 -o eth0 -j ACCEPT

-A OUTPUT -d 192.168.178.0/24 -o eth0 -j ACCEPT

-A OUTPUT -o eth0 -j DROP

-A OUTPUT -d 103.86.99.100/32 -o eth0 -j ACCEPT

-A OUTPUT -d 103.86.96.100/32 -o eth0 -j ACCEPT

-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

-A OUTPUT -o lo -j ACCEPT

-A OUTPUT -o tap+ -j ACCEPT

-A OUTPUT -o tun+ -j ACCEPT

-A OUTPUT -o nordlynx -j ACCEPT

-A OUTPUT -p udp -m udp --dport 53 -j ACCEPT

-A OUTPUT -p udp -m udp --dport 51820 -j ACCEPT

-A OUTPUT -p tcp -m tcp --dport 1194 -j ACCEPT

-A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT

-A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT

-A OUTPUT -d 172.17.0.0/16 -j ACCEPT

-A OUTPUT -d 192.168.178.0/24 -j ACCEPT

-A OUTPUT -d 104.17.50.74/32 -o eth0 -j ACCEPT

-A OUTPUT -d 104.17.49.74/32 -o eth0 -j ACCEPT


nat:

-P PREROUTING ACCEPT

-P INPUT ACCEPT

-P OUTPUT ACCEPT

-P POSTROUTING ACCEPT

-A POSTROUTING -o tap+ -j MASQUERADE

-A POSTROUTING -o tun+ -j MASQUERADE

-A POSTROUTING -o nordlynx -j MASQUERADE


mangle:

-P PREROUTING ACCEPT

-P INPUT ACCEPT

-P FORWARD ACCEPT

-P OUTPUT ACCEPT

-P POSTROUTING ACCEPT


raw:

-P PREROUTING ACCEPT

-P OUTPUT ACCEPT



+ nordvpn status


  

-
  

-
  
Status: Connected

Current server: be193.nordvpn.com

Country: Belgium

City: Brussels

Your new IP: 188.95.55.48

Current technology: NordLynx

Current protocol: UDP

Uptime: 0 seconds

+ wait 353

++ pidof nordvpnd

+ tail -f --pid=112 /var/log/nordvpn/daemon.log

-P INPUT ACCEPT

-P FORWARD ACCEPT

-P OUTPUT ACCEPT

-P POSTROUTING ACCEPT


raw:

-P PREROUTING ACCEPT

-P OUTPUT ACCEPT


```

**Additional context**
My Bandwith using this container is very slow or atleast slower than it should be.

I've run several speedtests in both my docker container(s) and windows here is an example:

Docker VPN Container using NordLynx
![Docker VPN Container using NordLynx](https://i.imgur.com/NHmUEcP.png)

Docker VPN Container using UDP
![Docker VPN Container using UDP](https://i.imgur.com/HE6DGu1.png)

Docker **Emby** (as an example for a different container on same hardware)
![Docker **Emby** (as an example for a different container on same hardware)](https://i.imgur.com/CESZlqJ.png)

Windows using same NordVPN Server
![Windows using same NordVPN Server](https://i.imgur.com/STZKrch.png)

Docker connection
![Docker connection](https://i.imgur.com/6CY0KEJ.png)

Windows connection
![Windows connection](https://i.imgur.com/lbzCMb4.png)

Some additional notes:
I've already tried different servers, in differenct countries, tried with CyberSec On/Off (likewise with different or no DNS environment variables). It doesnt seem like a bottleneck in my Ethernet (as my docker is running on a rpi4) as my Emby container gets full speed.

Please be aware that i've run again with DEBUG=on but after my initial testing and before I created this issue. Thats why it has connected to a different server as in my screenshots there.

Greetings

**Comment by cristiangauma** [comment]
I'm running into de same problem.

**Comment by bubuntux** [comment]
try adding 
```
    ulimits:                    # Recommended for High bandwidth scenarios
      memlock:
        soft: -1
        hard: -1
        ```
        
or restarting the container

**Comment by Reen68** [comment]
Already tried that, my first three or four tries were with the ulimits. Removed it afterwards to try without, that's why it ain't in my compose in the original issue.

Also tried restarting the container a lot of times now (as I've composed with different settings at least 20 times)

Tried different servers that I also tried on desktop and verified them to have a good speed.

**Comment by bubuntux** [comment]
i just start experiencing this.. will try to update the binary and see if that fixes it.

**Comment by bubuntux** [comment]
i just released a new version that fixed my speed issues.

**Comment by Reen68** [comment]
Yes still experiencing this. While getting 40-50MB/s with Nord on Desktop I max out at 10 MB/s using the docker image. Most of the time it's only 6MB/s.

**Comment by jensenkd** [comment]
same network, different host.  I'm working on a better speedtest setup for debugging

**Comment by bubuntux** [comment]
> > Oh yeah some parameters where renamed
> 
> If you update the readme on that repo with the proper params, I'll give it some testing

Yes the readme is updated in the other repo

**Comment by jensenkd** [comment]
![image](https://user-images.githubusercontent.com/170765/138340985-ee612e5f-9005-4f4d-ab93-16c78b9de1ea.png)

**Comment by bubuntux** [comment]
i merge the changes from the other repository, adding s6 and update to latest ubuntu + nordvpn client, those changes were reported to fix the bandiwth issues, so i'll close this issue

**Comment by bubuntux** [comment]
i reached some incredible speeds using https://github.com/bubuntux/nordlynx

**Comment by jensenkd** [comment]
switched back over and I can confirm @bubuntux 

Nice work!
