### ISSUE TITLE
NORDVPN needs to have settings applied first before attempting to login

### ISSUE THREAD

**Issue by caduceus313** [bubuntux/nordvpn#236]
**Issue:**
I live in a country where VPN is actively blocked.  I need to use Obfuscated servers or I cannot login.
Unfortunately your script is never able to execute lines 159-166:
`echo "[$(date -Iseconds)] Setting up $(nordvpn -version)"
[[ -n ${CYBER_SEC} ]] && nordvpn set cybersec ${CYBER_SEC}
[[ -n ${DNS} ]] && nordvpn set dns ${DNS//[;,]/ }
[[ -n ${FIREWALL} ]] && nordvpn set firewall ${FIREWALL}
[[ -n ${KILLSWITCH} ]] && nordvpn set killswitch ${KILLSWITCH}
[[ -n ${OBFUSCATE} ]] && nordvpn set obfuscate ${OBFUSCATE}
[[ -n ${PROTOCOL} ]] && nordvpn set protocol ${PROTOCOL}
[[ -n ${TECHNOLOGY} ]] && nordvpn set technology ${TECHNOLOGY}`

Because it attempts to login to NORD first on lines 152-156.
`echo "[$(date -Iseconds)] Logging in"
nordvpn logout > /dev/null
nordvpn login --username "${USER}" --password "${PASS}" || {
  echo "[$(date -Iseconds)] Invalid Username or password."
  exit 1`

So because Nord hasn't yet been configured to use Obfuscated servers with nordvpn set obfuscate on , the login always fails as we cannot reach the server.

**Expected behavior:**
NordVPN should be configured before attempting to login so that login to Obfuscated servers can actually occur.

**Comment by bubuntux** [comment]
@caduceus313  try the `master` tag 
docker run .... ghcr.io/bubuntux/nordvpn:master  
i moved the obfuscation setting before login in, so that should solve the problem.

**Comment by caduceus313** [comment]
I can see the obfuscation turned on this way, however, because the location to be connected to doesn't happen until line 186, the obfuscation still doesn't actually happen so when logging in to nordvpn on line 152, it will still fail as it isn't yet connected to an obfuscated server.     

I was able to open a console to the container and login manually by typing:
nordvpn set obfuscate on
nordvpn connect Obfuscated_Servers 

It then prompted me for a login and then a password, which isn't really conducive to a programatic approach.

**Comment by bubuntux** [comment]
i see... unfortunately this seems like an issue with the nordvpn binary itself and not the container, i would recommend create a ticket in nordvpn site, if you find a way to connect using programmatic approach lmk so i can added it into the container.

**Comment by caduceus313** [comment]
So actually it works fine the way you have it, if entered manually from the command line....
 while doing a trace:
`+ nordvpn login --username me@gmail.com --password 'Some1999!'
++ date -Iseconds
+ echo '[2021-08-10T03:09:21+03:00] Invalid Username or password.'
+ exit 1
[2021-08-10T03:09:21+03:00] Invalid Username or password.`

However, from the terminal of the container... typing the same command, works fine:
`root@cbbe970ec120:/# nordvpn login  --username me@gmail.com --password 'Some1999!'
Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.
root@cbbe970ec120:/# `

**Comment by bubuntux** [comment]
That is odd... Maybe we need a delay after changing the setting

**Comment by caduceus313** [comment]
`root@cbbe970ec120:/# time nordvpn login --username me@gmail.com --password 'Some1999!'
Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.

real    0m10.074s
user    0m0.006s
sys     0m0.005s
root@cbbe970ec120:/# `

**Comment by bubuntux** [comment]
i added a 3 second delay, wait for the build to finish and pull the latest master and try again

**Comment by caduceus313** [comment]
```
+ '[' -S /run/nordvpn/nordvpnd.sock ']'
++ date -Iseconds
++ nordvpn -version

+ echo '[2021-08-10T04:06:32+03:00] Pre settings NordVPN Version 3.10.0'

+ [[ -n 1.1.1.1,1.0.0.1 ]]
[2021-08-10T04:06:32+03:00] Pre settings NordVPN Version 3.10.0

+ nordvpn set dns 1.1.1.1 1.0.0.1
DNS is already set to '1.0.0.1, 1.1.1.1'.
+ [[ -n False ]]
+ nordvpn set cybersec False
CyberSec is already set to 'disabled'.
+ [[ -n on ]]
+ nordvpn set obfuscate on
Obfuscation is already set to 'enabled'.
+ [[ -z Somepass666!]]
++ date -Iseconds
[2021-08-10T04:06:32+03:00] Logging in
+ echo '[2021-08-10T04:06:32+03:00] Logging in'
+ nordvpn logout
+ nordvpn login --username me@gmail.com --password 'Somepass666!'
++ date -Iseconds
+ echo '[2021-08-10T04:07:18+03:00] Invalid Username or password.'
+ exit 1
[2021-08-10T04:07:18+03:00] Invalid Username or password.
```

**Comment by bubuntux** [comment]
i don't see the 3 sec delay in that last log, can you try to pull the image again and try again

**Comment by caduceus313** [comment]
```
+ service nordvpn start
++ date -Iseconds
[2021-08-10T17:13:42+03:00] Waiting for the service to start
+ echo '[2021-08-10T17:13:42+03:00] Waiting for the service to start'
+ attempt_counter=0
+ max_attempts=50
+ '[' -S /run/nordvpn/nordvpnd.sock ']'
+ '[' 0 -eq 50 ']'
+ attempt_counter=1
+ sleep 0.1
+ '[' -S /run/nordvpn/nordvpnd.sock ']'
+ '[' 1 -eq 50 ']'
+ attempt_counter=2
+ sleep 0.1
+ '[' -S /run/nordvpn/nordvpnd.sock ']'
++ date -Iseconds
++ nordvpn -version

+ echo '[2021-08-10T17:13:42+03:00] Pre-logging settings NordVPN Version 3.10.0'

[2021-08-10T17:13:42+03:00] Pre-logging settings NordVPN Version 3.10.0

+ [[ -n 1.1.1.1,1.0.0.1 ]]
+ nordvpn set dns 1.1.1.1 1.0.0.1
DNS is set to '1.0.0.1, 1.1.1.1' successfully.
+ [[ -n False ]]
+ nordvpn set cybersec False
CyberSec is already set to 'disabled'.
+ [[ -n on ]]
+ nordvpn set obfuscate on
Obfuscation is successfully set to 'enabled'.

3
+ [[ trace == trace+* ]]
+ set +x
[2021-08-10T17:13:45+03:00] Hiding user/password from the logs, set DEBUG=trace+ if you want to show them in the logs
[2021-08-10T17:13:45+03:00] Logging in
[2021-08-10T17:14:23+03:00] Invalid Username or password.
```

**Comment by caduceus313** [comment]
Again from the console of the container:
root@7f8dc0a78fa0:/# time nordvpn login --username "me@gmail.com" --password "Somepass555!"
Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.

real    0m7.875s
user    0m0.007s
sys     0m0.003s

**Comment by bubuntux** [comment]
not sure what else can we do, the container is doing the same as you through the command line, please lmk if you find a solution
