### ISSUE TITLE
Client no longer connecting

### ISSUE THREAD

**Issue by danps1** [bubuntux/nordvpn#280]
**Describe the bug**
Since latest update, the client is failing to connect to VPN.

**To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)
```
  nordvpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: nordvpn
    cap_add:
      - NET_ADMIN                        
    environment:
      - TZ=Australia/Sydney
      - USER=*****
      - PASS=*****
      - CONNECT=Australia
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.0.0/16
```

**Expected behavior**

A successful connection

**Logs**
```
Get "https://zwyr157wwiu6eior.com/v1/helpers/ips/insights": quic: performing request: curl: Couldn't connect to server

[services.d] done.

Password login is deprecated.

'nordvpn login --nordaccount' will become the default login method in the future.

You are already logged in.

Invalid Username or password.

[cmd] /bin/sh exited 1

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.
```
**Additional context**

I have not changed the password, and have double-checked the login details with a browser.

**Comment by bubuntux** [comment]
seems odd that it says that you are already logged in, are you mounting a volume that holds the nordvpn creds ? 
try creating a container from scratch

**Comment by bubuntux** [comment]
master tag should fix this issue

**Comment by danps1** [comment]
Have completely removed the container, and deleted images. No volume mounts used.
Recreated using `:master` tag. Still seeing the following...
```
2021/11/12 01:30:19 Technology set to: NORDLYNX

NordVPN App Connection Settings:

Technology: NORDLYNX

Protocol: UDP

Firewall: enabled

KillSwitch: disabled

Obfuscate: disabled

CyberSec: disabled

DNS: 

IPv6: disabled

Notify: disabled

Auto-connect: disabled


2021/11/12 01:30:19 Get "https://zwyr157wwiu6eior.com/v1/helpers/ips/insights": quic: performing request: curl: Couldn't connect to server

[services.d] done.

Password login is deprecated.

'nordvpn login --nordaccount' will become the default login method in the future.

You are already logged in.
Invalid Username or password.
[cmd] /bin/sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
```

**Comment by bubuntux** [comment]
the change still deploying.. https://github.com/bubuntux/nordvpn/actions/runs/1451258295 give it a few minutes

**Comment by danps1** [comment]
Great - that worked.
Thanks very much!

**Comment by azumukupoe** [comment]
I think it's broken again...

**Comment by Issam2204** [comment]
I'm experiencing this same issue.

**Comment by PsyKoMari** [comment]
Same here.
It worked for some days with the latest tag, then it stopped working.
I also tried pulling master tag but with no luck.

**Comment by Issam2204** [comment]
> 

Yep, I have the same error message as @PsyKoMari .

**Comment by Gandalf-** [comment]
I'm seeing potentially the same problem as @PsyKoMari and @Issam2204 
```
vpn_1_f4446282c8fd | [services.d] done.
Password login is deprecated.
vpn_1_f4446282c8fd | 'nordvpn login --nordaccount' will become the default login method in the future.
|2021/12/17 05:03:54 Get "https://zwyr157wwiu6eior.com/v1/helpers/ips/insights": quic: performing request: curl: Timeout was reached
\2021/12/17 05:03:55 Post "https://zwyr157wwiu6eior.com/v1/users/tokens": quic: performing request: curl: Timeout was reached
|2021/12/17 05:03:55 [Error] logging in: Bad Request: Invalid username
Username or password is not correct. Please try again.
vpn_1_f4446282c8fd | Invalid Username or password.
vpn_1_f4446282c8fd | [cmd] /bin/sh exited 1
vpn_1_f4446282c8fd | [cont-finish.d] executing container finish scripts...
vpn_1_f4446282c8fd | [cont-finish.d] done.
vpn_1_f4446282c8fd | [s6-finish] waiting for services.
vpn_1_f4446282c8fd | [s6-finish] sending all processes the TERM signal.
vpn_1_f4446282c8fd | [s6-finish] sending all processes the KILL signal and exiting.
```
The credentials are still valid unless there's some blocking going on - I just tried them through the web portal.

**Comment by bubuntux** [comment]
migrate to https://github.com/bubuntux/nordlynx seems like nordvpn deprecated the cli headless login

**Comment by PsyKoMari** [comment]
I can confirm, @bubuntux is right.
Migrating to nordlynx container fixed all my problems.
BTW It was not that simple to obtain the WG Private Key because in order to do that you still need to login with username and password from cli, which is "maybe deprecated".

The only solution I found was to install nordvpn to a linux VM, login via `nordvpn login --nordaccount`, completing the login with the browser and only then, obtaining the private key.
